spring:
  application:
    name: submission3
  cloud:
    loadbalancer:
      retry:
        enabled: false
    openfeign:
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 5000
            loggerLevel: basic

peer-to-peer:
  node-id: happy-lime
  broadcast:
    address: 192.168.1.255
    port: 8888
    rate: 5s
  tcp-port: 9090
  notification:
    rate: 10s
